### PR TITLE
should pass states correctly to all subscribers when actions are dispatched recursively

### PR DESCRIPTION
**Pull request by markx**

### CODE REVIEW

**Comment by bedorlan** [comment]
```
diff --git a/src/index.js b/src/index.js
index 16643f4..3b7907f 100644
--- a/src/index.js
+++ b/src/index.js
@@ -36,8 +36,21 @@ const enhancer = (createStore) => {
       prevState = curState
     })
 
+    const theDispatcher = store.dispatch
+    const postponedActions = []
+    let sequence = 0
+    let recursionLevel = 0
+
     store.whenever = (selector, assertion, callback) => {
+
+      const myId = ++sequence
       return store.subscribe(() => {
+
+        ++recursionLevel
+        store.dispatch = function() {
+          postponedActions.push(arguments)
+        }
+
         curState = store.getState()
         const curStateSubtree = getStateSubtree(curState, selector)
         const prevStateSubtree = getStateSubtree(prevState, selector)
@@ -45,6 +58,18 @@ const enhancer = (createStore) => {
         if (conditionsAreMet(assertion, curStateSubtree, prevStateSubtree)) {
           callback(curStateSubtree, prevStateSubtree)
         }
+
+        // only the last one subscribed without recursion, should dispatch the actions
+        if (myId === sequence && recursionLevel === 1) {
+          for (let i = 0; i < postponedActions.length; ++i) {
+            theDispatcher.apply(store, postponedActions[i])
+          }
+
+          postponedActions.length = 0
+          store.dispatch = theDispatcher
+        }
+
+        --recursionLevel
       })
     }
 
diff --git a/test/regression.js b/test/regression.js
index fe4657e..bc831b7 100644
--- a/test/regression.js
+++ b/test/regression.js
@@ -76,7 +76,7 @@ describe('regression', () => {
     const store = redux.createStore(reducer, reduxWhenever)
 
     store.whenever('foo.bar', () => true, (curState, prevState) => {
-      if (curState === 3) {
+      if (curState === 5) {
         return;
       }
       store.dispatch({
@@ -90,9 +90,12 @@ describe('regression', () => {
     const callback = jest.fn()
     store.whenever('foo.bar', () => true, (curState, prevState) => {
       callback(curState, prevState)
-      if (curState === 3) {
+      if (curState === 5) {
+        expect(callback).toHaveBeenCalledWith(1, undefined)
         expect(callback).toHaveBeenCalledWith(2,1)
         expect(callback).toHaveBeenCalledWith(3,2)
+        expect(callback).toHaveBeenCalledWith(4,3)
+        expect(callback).toHaveBeenCalledWith(5,4)
       }
     })
 
@@ -102,5 +105,7 @@ describe('regression', () => {
         foo: { bar: 1 }
       }
     })
+
+    expect(callback).toHaveBeenCalledTimes(5)
   })
 })

```

**Comment by bedorlan** [comment]
i couldn't push to the pull request

**Comment by caiogondim** [comment]
@bedorlan So sorry for the late reply and....WOW
That was a beautiful solution for the issue.
Thanks a lot for that.

**Comment by caiogondim** [comment]
Just gave you commit access, so can push to PRs.

**Pull request merged**
